#![doc = include_str!("../../README.md")]
#[cfg(feature = "cli")]
pub mod cli;
pub mod db;
pub mod errors;
pub mod parser;
pub mod processor;
#[cfg(feature = "reporters")]
pub mod reporters;
pub mod walk;
